version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_AIRFLOW_DB}
        ports:
            - "5432:5432"
               
    webserver:
        build: .
        #image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_AIRFLOW_DB}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            - ./spark:/usr/local/spark/conf
            - ./hadoop:/usr/local/hadoop/etc/hadoop
            - ./src:/home/ubuntu/cookie_consent/src
            - ./deps.zip:/home/ubuntu/cookie_consent/deps.zip
            - ./stop_cluster.sh:/home/ubuntu/cookie_consent/stop_cluster.sh
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
